name: Magento 2 Integration Tests (ExtDN)

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: read

concurrency:
  group: m2-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-php81:
    name: Magento 2 Integration (PHP 8.1, 2.4.6-p3)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          xpack.security.enabled: 'false'
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl -sSf localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: Mageproxy_Connector
          composer_name: mageproxy/connector-magento2
          magento_version: '2.4.6-p3'
          composer_version: '2'
          phpunit_file: '.github/extdn/phpunit.xml'
